In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
data=sns.load_dataset('iris')

In [5]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
data.shape

(150, 5)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [9]:
x=data.iloc[:,:4]
type(x)

pandas.core.frame.DataFrame

In [10]:
y=data['species']
type(y)

pandas.core.series.Series

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=5)

In [12]:
x_train.shape

(112, 4)

In [13]:
x_train.shape

(112, 4)

In [14]:
type(x_train)

pandas.core.frame.DataFrame

In [15]:
type(y_train)

pandas.core.series.Series

In [16]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_test = sc.fit_transform(x_test)
x_train = sc.fit_transform(x_train)


In [17]:
type(x_test)


numpy.ndarray

In [18]:
x_test

array([[-0.06157644, -0.91065065,  0.04583364, -0.03211399],
       [ 0.30788222, -1.19429593,  1.03278471,  0.23907083],
       [-0.06157644, -0.62700536,  0.74250498,  1.59499494],
       [-1.78571685,  0.50757577, -1.46362094, -1.3880381 ],
       [ 1.66256397,  1.6421569 ,  1.32306444,  1.73058735],
       [-1.16995242, -1.7615865 , -0.30250203, -0.30329881],
       [-1.16995242, -0.0597148 , -1.40556499, -1.3880381 ],
       [ 0.06157644,  0.50757577,  0.56833715,  0.78144047],
       [-1.04679953, -0.0597148 , -1.2894531 , -1.3880381 ],
       [-0.55418799, -0.0597148 ,  0.39416931,  0.37466324],
       [-0.30788222, -0.0597148 ,  0.39416931,  0.37466324],
       [ 0.55418799, -0.62700536,  0.74250498,  0.37466324],
       [ 1.53941108, -0.0597148 ,  1.20695255,  1.18821771],
       [ 1.78571685, -0.34336008,  1.43917633,  0.78144047],
       [-1.04679953,  1.07486634, -1.2894531 , -1.11685328],
       [-0.92364665,  0.79122105, -1.23139716, -0.98126087],
       [ 0.55418799, -0.

In [19]:
type(x_train)

numpy.ndarray

In [20]:
x_train

array([[-1.01363949,  0.93918045, -1.37564401, -1.16191449],
       [ 0.67360756,  0.28448205,  0.88265029,  1.44598977],
       [-0.04949832, -0.80668197,  0.76973558,  0.92440892],
       [-0.29053361, -1.24314757,  0.09224729, -0.11875278],
       [-0.89312185,  0.93918045, -1.31918665, -1.16191449],
       [-0.89312185,  1.59387886, -1.20627193, -1.2923097 ],
       [ 0.79412521, -0.58844916,  0.48744879,  0.40282807],
       [ 0.43257227, -0.58844916,  0.60036351,  0.79401371],
       [ 0.07101933, -0.15198356,  0.26161936,  0.40282807],
       [ 1.0351605 ,  0.50271485,  1.10847973,  1.18519935],
       [ 2.24033697,  1.59387886,  1.6730533 ,  1.31559456],
       [-0.53156891,  0.72094765, -1.14981458, -1.2923097 ],
       [ 0.55308991, -1.24314757,  0.71327822,  0.92440892],
       [-1.01363949,  0.28448205, -1.43210136, -1.2923097 ],
       [-1.49571008,  0.72094765, -1.31918665, -1.16191449],
       [-0.17001597,  2.90327568, -1.26272929, -1.03151927],
       [-0.7726042 ,  0.

In [21]:
from sklearn.naive_bayes import GaussianNB
nb_model=GaussianNB()

In [22]:
type(nb_model)
nb_model.fit(x_train,y_train)

GaussianNB()

In [23]:
y_predict=nb_model.predict(x_test)
y_predict

array(['versicolor', 'versicolor', 'virginica', 'setosa', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'setosa',
       'setosa', 'virginica', 'virginica', 'setosa', 'setosa',
       'versicolor', 'virginica', 'setosa', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'setosa', 'virginica'], dtype='<U10')

In [24]:
from sklearn.metrics import accuracy_score
print("Accuracy score is :", accuracy_score(y_test,y_predict))


Accuracy is : 0.9210526315789473


In [25]:
from sklearn.metrics import precision_score
print("Precision score is :", precision_score(y_test,y_predict,average='macro'))

Precision score is : 0.9252525252525253


In [26]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix is :", confusion_matrix(y_test,y_predict))

Confusion matrix is : [[12  0  0]
 [ 0 13  1]
 [ 0  2 10]]


In [27]:
from sklearn.metrics import classification_report
print("Classification report is :", classification_report(y_test,y_predict))

Classification report is :               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.87      0.93      0.90        14
   virginica       0.91      0.83      0.87        12

    accuracy                           0.92        38
   macro avg       0.93      0.92      0.92        38
weighted avg       0.92      0.92      0.92        38



In [ ]:
x_new=[[2,4,5,1]]
x_new=sc.fit_transform(x_new)
new_predict=nb_model.predict(x_new)
