In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df=pd.read_csv('train.csv')
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [25]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [26]:
df.title[0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [27]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [28]:
import nltk
from nltk.corpus import stopwords

In [30]:
stopword=stopwords.words('english')
stopword

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [31]:
a='once upon a time, there was a Greek King, Midas. He was very rich and had lots of Gold. He had a daughter, who he loved a lot.One day, Midas found an angel in need of help. He helped her and in return she agreed to grant a wish.'

In [32]:
from nltk.tokenize import sent_tokenize
a=a.lower()
print(a)

once upon a time, there was a greek king, midas. he was very rich and had lots of gold. he had a daughter, who he loved a lot.one day, midas found an angel in need of help. he helped her and in return she agreed to grant a wish.


In [33]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [38]:
b=sent_tokenize(a)
b

['once upon a time, there was a greek king, midas.',
 'he was very rich and had lots of gold.',
 'he had a daughter, who he loved a lot.one day, midas found an angel in need of help.',
 'he helped her and in return she agreed to grant a wish.']

In [35]:
from nltk.tokenize import word_tokenize

In [37]:
c=word_tokenize(a)
c

['once',
 'upon',
 'a',
 'time',
 ',',
 'there',
 'was',
 'a',
 'greek',
 'king',
 ',',
 'midas',
 '.',
 'he',
 'was',
 'very',
 'rich',
 'and',
 'had',
 'lots',
 'of',
 'gold',
 '.',
 'he',
 'had',
 'a',
 'daughter',
 ',',
 'who',
 'he',
 'loved',
 'a',
 'lot.one',
 'day',
 ',',
 'midas',
 'found',
 'an',
 'angel',
 'in',
 'need',
 'of',
 'help',
 '.',
 'he',
 'helped',
 'her',
 'and',
 'in',
 'return',
 'she',
 'agreed',
 'to',
 'grant',
 'a',
 'wish',
 '.']

In [40]:
from nltk.stem import PorterStemmer
porter=PorterStemmer()
stemmed_word=[porter.stem(word) for word in c]
stemmed_word

['onc',
 'upon',
 'a',
 'time',
 ',',
 'there',
 'wa',
 'a',
 'greek',
 'king',
 ',',
 'mida',
 '.',
 'he',
 'wa',
 'veri',
 'rich',
 'and',
 'had',
 'lot',
 'of',
 'gold',
 '.',
 'he',
 'had',
 'a',
 'daughter',
 ',',
 'who',
 'he',
 'love',
 'a',
 'lot.on',
 'day',
 ',',
 'mida',
 'found',
 'an',
 'angel',
 'in',
 'need',
 'of',
 'help',
 '.',
 'he',
 'help',
 'her',
 'and',
 'in',
 'return',
 'she',
 'agre',
 'to',
 'grant',
 'a',
 'wish',
 '.']

In [41]:
import nltk
nltk.download('wordnet')

import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [43]:
from nltk.stem import WordNetLemmatizer

lemmatizer=WordNetLemmatizer()
word_lemmatizer=[lemmatizer.lemmatize(word) for word in stemmed_word]
word_lemmatizer

['onc',
 'upon',
 'a',
 'time',
 ',',
 'there',
 'wa',
 'a',
 'greek',
 'king',
 ',',
 'mida',
 '.',
 'he',
 'wa',
 'veri',
 'rich',
 'and',
 'had',
 'lot',
 'of',
 'gold',
 '.',
 'he',
 'had',
 'a',
 'daughter',
 ',',
 'who',
 'he',
 'love',
 'a',
 'lot.on',
 'day',
 ',',
 'mida',
 'found',
 'an',
 'angel',
 'in',
 'need',
 'of',
 'help',
 '.',
 'he',
 'help',
 'her',
 'and',
 'in',
 'return',
 'she',
 'agre',
 'to',
 'grant',
 'a',
 'wish',
 '.']

In [44]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [46]:
from nltk import pos_tag
pos_var=pos_tag(word_lemmatizer)
for word_lemmatizer,pos_tag in pos_var:
  print(f"{word_lemmatizer}:{pos_tag}")

onc:RB
upon:IN
a:DT
time:NN
,:,
there:EX
wa:VBZ
a:DT
greek:JJ
king:NN
,:,
mida:NN
.:.
he:PRP
wa:VBD
veri:NN
rich:JJ
and:CC
had:VBD
lot:NN
of:IN
gold:NN
.:.
he:PRP
had:VBD
a:DT
daughter:NN
,:,
who:WP
he:PRP
love:VB
a:DT
lot.on:JJ
day:NN
,:,
mida:NN
found:VBD
an:DT
angel:NN
in:IN
need:NN
of:IN
help:NN
.:.
he:PRP
help:VBD
her:PRP
and:CC
in:IN
return:NN
she:PRP
agre:VBD
to:TO
grant:VB
a:DT
wish:NN
.:.


In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
d0="good boy"
d1="girl good"
d2="boy girl good"
tfidf=TfidfVectorizer()
string=[d0,d1,d2]
string

['good boy', 'girl good', 'boy girl good']

In [48]:
result=tfidf.fit_transform(string)
print("tfidf values:|")
print(result)

tfidf values:|
  (0, 0)	0.7898069290660905
  (0, 2)	0.6133555370249717
  (1, 1)	0.7898069290660905
  (1, 2)	0.6133555370249717
  (2, 1)	0.6198053799406072
  (2, 0)	0.6198053799406072
  (2, 2)	0.48133416873660545


In [52]:
for feature_name, idf_value in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    print(feature_name, ":", idf_value)


boy : 1.2876820724517808
girl : 1.2876820724517808
good : 1.0


In [53]:
print("\nWord Indexes:")
print(tfidf.vocabulary_)


Word Indexes:
{'good': 2, 'boy': 0, 'girl': 1}


In [54]:
print("tfidf values In Matrix Form:\n")
print(result.toarray())

tfidf values In Matrix Form:

[[0.78980693 0.         0.61335554]
 [0.         0.78980693 0.61335554]
 [0.61980538 0.61980538 0.48133417]]
